### ISSUE TITLE
Gaming

### ISSUE THREAD

**Issue by Nottijay** [Pittvandewitt/Wavelet#106]
It doesn't work on battle ground mobile gaming to help increase or balance footstep sound bar gun sound and other sounds  I saw increasing bass and reducing treble makes the footstep sound increase but not effective in game like pubg mobile or call of duty mobile

**Comment by Pittvandewitt** [comment]
Games in general do not have support for audio processing implemented. No audio sessions are started either, so using the enhanced session detection mode won't help either. Because of these reasons, it is impossible to support games.
On a side note; audio processing comes at a cost of latency, which I can imagine is undesirable in games. Most effects in Wavelet add a delay of +-22ms, if you have buffer size set to the smallest option. The latency does not stack though.
