### ISSUE TITLE
Bass booster option not showing up at all

### ISSUE THREAD

**Issue by JordyTearWater** [Pittvandewitt/Wavelet#108]
The bass booster option isn't showing up at all in the app for me ever since i switched phones.

Im currently using an LG V60 running android 11 and using the app to listen to spotify. All the other options are available, even the bass tuner, but the bass boost refuses to show up. 

The option doesn't show up on any of my headphones.

**Comment by Pittvandewitt** [comment]
The bass booster is not available on devices running Android 10 and up, because this audio effect was changed for some reason with this Android update. Now it no longer meets the quality I wish to provide in Wavelet. On the up side, this Android update allows for setting a lower buffer size and bass tuner frequency.
