### ISSUE TITLE
[Feature request] Parametric EQ edit

### ISSUE THREAD

**Issue by S0und** [Pittvandewitt/Wavelet#109]
Would you consider a feature that allows the user to edit the already imported Auto EQ? Similarly how can you change the EQ in Peace. This would be a great **paid** feature for audiophiles. I'm aware that i can change the `AutoEQ strength`, but i want to edit certain part of the imported EQ. For example the EQ adds +3db to 4k and  +4db to 7k, but i rather have those specific frequencies at a lower db level, but keep the rest of the EQ intact.

I would imagine that below the EQ graph we would have the values at makes up the EQ in a list. In each row we could edit the Q value, frequency and the db.

**Comment by Pittvandewitt** [comment]
It is possible to grab the GraphicEq.txt file for your headphone and edit the gain strength manually, although this is not recommended because it is very error prone: https://github.com/jaakkopasanen/AutoEq/tree/master/results
You can then import the edited file in Wavelet.

Alternatively you can check out the instructions on how to import files in Wavelet, which will explain how you can create custom files using the AutoEq tool: https://pittvandewitt.github.io/Wavelet/Import
