### ISSUE TITLE
Latency

### ISSUE THREAD

**Issue by jsadecki1** [Pittvandewitt/Wavelet#110]
Hello, I've got Wavelet on a galaxy s21 plus 5g with latest update and was wondering if there's any way around the latency before the wavelet settings kick in when i play a song on Spotify

The song plays without my wavelet setting first and then they kock in after a second, with every song

I had an s1p plus before and this didn't happen

Already tried adjusting the buffer to no avail

Looking forward to hearing from yous, thank you

**Comment by Pittvandewitt** [comment]
There is no way to adjust the delay before settings become active. This is because Wavelet relies on the OS to be notified when a new music session starts, which happens externally.
Perhaps you could try using the enhanced session detection mode: [pittvandewitt.github.io/Wavelet](https://pittvandewitt.github.io/Wavelet/#enhanced-session-detection)

**Comment by jsadecki1** [comment]
OK thank you very much, I will have a go at that then, have a nice day



Sent from my Galaxy



-------- Original message --------
From: "Thomas W." ***@***.***>
Date: 23/09/2021 7:34 pm (GMT+00:00)
To: Pittvandewitt/Wavelet ***@***.***>
Cc: jsadecki1 ***@***.***>, Author ***@***.***>
Subject: Re: [Pittvandewitt/Wavelet] Latency (#110)


There is no way to adjust the delay before settings become active. This is because Wavelet relies on the OS to be notified when a new music session starts, which happens externally.
Perhaps you could try using the enhanced session detection mode: pittvandewitt.github.io/Wavelet<https://pittvandewitt.github.io/Wavelet/#enhanced-session-detection>
