### ISSUE TITLE
[Request] More reverberation options

### ISSUE THREAD

**Issue by Tvde1** [Pittvandewitt/Wavelet#120]
The reverberation options now are quite limited. I would like to customize the reverberation (wet, dry ratio, bounces, room size, etc) even further to create more unique sounds

**Comment by Pittvandewitt** [comment]
The environmental reverb contains the properties you mention, but it cannot be used by global equalizer applications because this is an auxillary effect type and must be attached to the MediaPlayer object explicitly by the music player itself.
According to the documentation, it shouldn't be possible for the preset reverb to be used by global eq applications either, but it seems to work anyway, unlike the environmental reverb.

I would have loved for more reverb options to be possible, but that is not the case unfortunately.
