### ISSUE TITLE
Small bug with the EQ

### ISSUE THREAD

**Issue by Netherquark** [Pittvandewitt/Wavelet#124]
![Screenshot_20211202-124759458 (1).jpg](https://user-images.githubusercontent.com/65618735/144376139-ec20b0dc-7dcf-412c-9b8c-d805d54eba3b.jpg)

Pretty small but looks like the blue highlight loads behind the eq slider showing that bug

**Comment by Pittvandewitt** [comment]
The design specification indeed draws the ripple above the track. The issue is ultimately an issue in the Slider implementation from the material components library. I recommend reporting the issue over there: https://github.com/material-components/material-components-android/issues
https://material.io/components/sliders#anatomy

**Comment by Netherquark** [comment]
hey there could you check this out?

> Thanks so much for the explanation and video, that really helped explain the bug. I changed the issue title to more clearly explain the bug. I tried to reproduce the issue in our catalog but I'm not seeing the issue on our end (see video attached). It's possible that the Wavelet code modifies the Material slider, resulting in this bug. It's also possible that the slider is not a Material slider or that there is an underlying issue with the Material slider that the Wavelet code somehow triggers. I recommend reaching out to the Wavelet developers to let them know about the bug. If they'd like, they can update this issue with their code and we can help them troubleshoot the bug

-from the issue I opened as you asked me to
