### ISSUE TITLE
Issue with play store

### ISSUE THREAD

**Issue by leleobhz** [Pittvandewitt/Wavelet#131]
Hello!

I've paid out features on wavelet but a lot of times I got rollback to free version. If I click on feature, it opens wallet dialog but store return error because I've already paid.

![Screenshot_20211230-130456_Google Play Store.png](https://user-images.githubusercontent.com/201189/147768304-c5830962-c433-4cc9-b78d-e16b1ed6ebf1.png)

Clean cache and force close does not help.

Can you implement a function to re-check Store payments?

**Comment by Pittvandewitt** [comment]
Have you tried removing the cache and data from the Google Play store and Google Play Services applications? This forces your purchases to be fetched again.

**Comment by leleobhz** [comment]
@Pittvandewitt I removed the cache but not the data - because I dont want to loose parameters. Reboot usually resolves, but unavailability of a button to fetch pucharses again is a bit of pain :(

**Comment by Pittvandewitt** [comment]
I've seen this issue occur only if the purchase is made with the account that is not the primary account on your device. Wavelet needs to be installed by the primary user because the app can only operate properly if as single installation is active.
If you need more support, please send me an email instead.
