### ISSUE TITLE
Wavelet settings on a per Bluetooth device basis

### ISSUE THREAD

**Issue by Netherquark** [Pittvandewitt/Wavelet#132]
So you mustve seen how Spotify scrapes the Bluetooth device name and displays it. I presume there is a public API in android for the same. Could you implement support for it with individual settings saved for each device? Presently whatever settings are selected for one BT device are applied universally. This is kinda irritating because I have the total opposite EQ for my BT earphones and for the 5.1 speaker system. 

Another possible cool thing could be scraping the device name and automatically asking if you want to enable AutoEQ for that device (if available obviously). Eg imagine you get WH1000XM3s and wavelet shows a pop up after pairing asking you if you want EQ.

**Comment by Pittvandewitt** [comment]
I am not sure if I misunderstand you or if you missed something, because Wavelet already saves and restores your configuration based on the connected device before it was first launched.

Matching the found title with an entry from the AutoEq database has to happen with a fuzzy search pattern, which is error prone. This will confuse users who are not experienced in setting up equalization. There are also many cases where multiple compensations can be applied to a single device, e.g. when the device is set up for a treble preset or vocal preset, or when a certain IEM as multiple filters that can be used.
