### ISSUE TITLE
I found my headphone model in AutoEq results folder's recommended headphones list, but can't find it in the Wavelet.

### ISSUE THREAD

**Issue by NomaanMalick** [Pittvandewitt/Wavelet#14]
[Here it is in the results folder.](https://github.com/jaakkopasanen/AutoEq/blob/master/results/referenceaudioanalyzer/referenceaudioanalyzer_siec_harman_in-ear_2019v2/Sennheiser%20CX%20180%20Street%20II) So, why can't I find it in Wavelet?

**Comment by Pittvandewitt** [comment]
[Not all results from reference audio analyzer look reliable to me](https://github.com/jaakkopasanen/AutoEq/tree/master/results/referenceaudioanalyzer/referenceaudioanalyzer_hdm1_harman_over-ear_2018/Philips%20SHG7980). Because of this, I chose not to include their results. I am working on a feature that allows you import the GraphicEQ data instead.

**Comment by NomaanMalick** [comment]
Is there any way I can find out whether my headphones' data on there is reliable or not?
