### ISSUE TITLE
Why is YT Music not supported but Youtube Music is?

### ISSUE THREAD

**Issue by johnLegasse** [Pittvandewitt/Wavelet#159]
From my understanding YT Music (vanced) is supposed to be a repackaged cleaned version of Youtube Music, 
I would expect both app to be pretty close ergo working the same with Wavelet.

Can you provide some info about that?

**Comment by KVK792844** [comment]
Wavelet main page (without legacy enabled) still shows that no music sessions are active even though YT music (Vanced) is playing in the background.

![Screenshot_20220308-103215__01](https://user-images.githubusercontent.com/87488404/157169578-b5c64ae1-256b-4e5b-89d9-6ba97cc54174.jpg)


![Screenshot_20220308-103117__01](https://user-images.githubusercontent.com/87488404/157169595-16b0c218-200c-4f89-8f78-7426577b8432.jpg)


![Screenshot_20220308-103123](https://user-images.githubusercontent.com/87488404/157169608-16867d2f-dc75-4aeb-81d6-1ab57549c93e.jpg)

**Comment by Pittvandewitt** [comment]
This must be because YT Music vanced does not properly broadcast its audio sessions. This is an issue with their application and not something I can fix. For a bit better explanation please refer to this page: https://pittvandewitt.github.io/Wavelet/#legacy-mode

I recommend enabling the enhanced session detection mode to work around it.
