### ISSUE TITLE
Wavelet and AutoEq not in sync (by at least 8 days)

### ISSUE THREAD

**Issue by Wobbley** [Pittvandewitt/Wavelet#17]
Hey

I saw that you answered in a review that the Eq data is synced with AutoEq data whenever it is updated. Not sure if the update process is manual action or an automatic update is failing, however AutEq has been updated with some models that Wavelet is missing. Mainly Sennheiser Momentum True Wireless 2, I know a couple of people are waiting for that model to be added, including myself.

Enjoying Wavelet so far, keep up the good work :clap:

**Comment by Pittvandewitt** [comment]
The database is synchronized manually and will be updated to the latest state whenever an update of Wavelet is released. It takes a little longer than usual because I have to test some significant changes and I want to make sure I made no errors.
The momentum TWS 2 will be added with the new update.
