### ISSUE TITLE
[Feature request] Per headphone model AutoEQ strength

### ISSUE THREAD

**Issue by aetha** [Pittvandewitt/Wavelet#236]
Hi there, amazing app, it's become indispensable to my listening experience. I have a few different headphones on hand and found AutoEQ presets for them all.

So that's neat but I found I have a different preference for the AutoEQ strength per headphones. Just wondering if you'd be willing to store that setting separately for each model, so it's not needed to change it each time the model is switched.

**Comment by Pittvandewitt** [comment]
I feel a bit confused about your message, because the AutoEq strength setting is already saved and restored together with the AutoEq preset you chose for your headphones.
Whenever you connect different headphones, this setting is saved for the next time you connect the same headphones.
You can check which headphones are detected by the device name displayed in the notification.
