### ISSUE TITLE
[Suggestion] Add Profile Saving & Loading

### ISSUE THREAD

**Issue by LokeYourLord** [Pittvandewitt/Wavelet#24]
So it would be great if it was possible to save and load profiles just like as with Viper4Android, because for some reason sometimes my settings get completely wiped and thus I need to manually readjust the Graphical Equalizer and that really quickly becomes annoying. Besides, it would still be great to have if you have different profiles for different Platforms/Songs.

Best Regards, -Loke

**Comment by Pittvandewitt** [comment]
You could create custom compensation data with the AutoEq tool as described in the article mentioned in [this link](https://pittvandewitt.github.io/Wavelet/Import) and load it whenever you like. Furthermore, your configuration is saved and restored automatically based on the connected device.
The issue of settings getting wiped should be fixed in the latest update.
I am not considering adding different configurations per platform or song. That would definitely become annoying quickly, let alone creating a user interface for it.

**Comment by LokeYourLord** [comment]
@Pittvandewitt You've greatly misunderstood the point here it seems. I want a feature just like Viper4Android has it where you can just export the currently marked options and their individual settings (basically the entire Profile), like how you configured Base Level, the Equalizer, etc, into an XML file or whatever. That way, when I change my Phone later, or want to use the same settings for another pair of Headphones, I won't need to set it up again all the way from the beginning.

**Comment by LokeYourLord** [comment]
@Pittvandewitt Issue not resolved, please reopen this.

**Comment by Pittvandewitt** [comment]
I did understand the point correctly. I am not considering implementing a way to import or export configurations other than the AutoEq import functionality. The difference with V4A is that in Wavelet all features are available dynamically, which makes it a headache to import settings the way V4A does. Perhaps after migrating to [Datastore](https://developer.android.com/topic/libraries/architecture/datastore) (when it reaches stable) a clean solution would be possible. 

If you switch phones, you can make use of the Google backup and restore function. It will transfer your current configuration automatically.
