### ISSUE TITLE
BassBoost and Virtualization Issues

### ISSUE THREAD

**Issue by BillisC** [Pittvandewitt/Wavelet#28]
Hi there, in the latest version bass boost and virtualization highly reduce the volume of the music while using Spotify. In legacy mode they seem not to have any effect at all or at least that's what it looks like. 
Similar thing happens in Poweramp. Both options work but reduce the volume a lot.

My phone is Redmi Note 8 (rooted & custom rom)

If I can help you in any way please tell me.

**Comment by BillisC** [comment]
Alright so in latest virtualization causes minimal reduce for some odd reason but bass boost is still left. Yes they all worked in 20.6
I understand that nonroot is a challenging thing but please do something it's been a month

**Comment by Pittvandewitt** [comment]
The bass booster causing a dip in volume seems to be a change made in Android 10. It used to sound much better on Android 9.
https://android.googlesource.com/platform/frameworks/av/+log/refs/heads/master/media/libeffects/lvm/lib/Bass/src

Effects not working in legacy mode is not a big surprise; It's called legacy mode for a reason. Legacy mode exists because it adds support for all music audio on some devices.
