### ISSUE TITLE
Wavelet stuck on disconnected device

### ISSUE THREAD

**Issue by fredericbellavance** [Pittvandewitt/Wavelet#29]
Often, when I shutdown my headphones and disable Bluetooth, Wavelet continues to believe my headphones are connected, causing equalization to be applied to devices who really don't need it.

Only workaround is to reboot cellphone, which is annoying to say the least.

**Comment by Pittvandewitt** [comment]
This issue should be fixed in the latest public beta: https://play.google.com/apps/testing/com.pittvandewitt.wavelet
Feel free to reopen this issue if it doesn't appear to be resolved.

**Comment by rcdailey** [comment]
I'm still seeing the issue with 20.09 installed. I have a "Speaker connected" ongoing notification with no Bluetooth audio devices connected.

**Comment by fredericbellavance** [comment]
@rcdailey I believe this isn't the issue I reported.

The problem was that even when I was on the phone built-in speaker, the notification said that my headphones/soundbar were connected even with Bluetooth disabled.

If it says " speaker connected " then the app correctly believes that there are no devices connected apart from the phone's built-in speaker, so to me it seems this is expected behavior.

**Comment by rcdailey** [comment]
Ah, that's possible. I simply assumed that it shouldn't show that notification for the built-in speaker. After all, most of the time the ongoing notification only appears when I have my bluetooth headphones connected. When I disconnect them, normally, that notification disappears. I prefer the notification *not* be active for the built-in speaker; otherwise it will be visible 100% of the time (and I don't even listen to music using my built-in speaker).

I'd like feedback from the dev on whether or not this is a feature or a bug, as well as if there's a way to exclude devices in case it's the former.

**Comment by AlessandroGandolfi** [comment]
I keep having this error and it's really annoying since the equalizer is completely set to different values with my phone or car speakers. Is there any solution?

I'm on the latest stable app version on a S22 Exynos, A12 April patch (it happened previously too).

I tried now to get into the beta to see if it fixed, for now it is a hassle to reboot everytime it happens.

If it gets resolved I would be glad to buy the pro version!
