### ISSUE TITLE
Questions about Preamp and a Bug

### ISSUE THREAD

**Issue by dogusaltin** [Pittvandewitt/Wavelet#325]
Does the preamp auto adjust itself for the imported EQ profiles, cause I hear no changes in sound volume when EQ is enabled? Like if a squig EQ profile recommends -6dB, does Wavelet apply this on its own?

If not, can the automatic post-gain in the limiter exceed -5dB limit, which is the lowest it can go when  tried to adjust manually?

Also a bug that occured out of nowhere: I have been applying negative preamps through the channel balance section but today it has started to distort the sound out of nowhere at -6dB. Totally unlistenable, full of bloat and bass.

**Comment by Pittvandewitt** [comment]
> Does the preamp auto adjust itself for the imported EQ profiles, cause I hear no changes in sound volume when EQ is enabled? Like if a squig EQ profile recommends -6dB, does Wavelet apply this on its own?

Pre-amp is not adjusted. Wavelet normalizes the imported data at 0dB. This is to prevent people from accidentally applying all +100dB gains for example.

> If not, can the automatic post-gain in the limiter exceed -5dB limit, which is the lowest it can go when tried to adjust manually?

It can. Automatic post-gain brings all frequencies down, so that the max boost is 0dB. I recommend this option over channel balance if your goal is to apply a pre-amp. It also takes all other features into account, such as the bass tuner and the graphic equalizer.

> Also a bug that occured out of nowhere: I have been applying negative preamps through the channel balance section but today it has started to distort the sound out of nowhere at -6dB. Totally unlistenable, full of bloat and bass.

Noted. I'm working on a possible fix

**Comment by Pittvandewitt** [comment]
The bug with channel balance was resolved in version 24.11

**Comment by dogusaltin** [comment]
Awesome, thanks 🙏🏻

> The bug with channel balance was resolved in version 24.11

Awesome, thanks 🙏🏻

**Comment by mackers04** [comment]
Looking forward to this fix a lot! :) Wavelet was working fine for a while until last night. AutoEQ is doing some bass movements (about +3db) that crushes the output to my IEMs and Bluetooth Truly Wireless earbuds
