### ISSUE TITLE
Stacking Poweramps

### ISSUE THREAD

**Issue by BillisC** [Pittvandewitt/Wavelet#33]
Hi there, I've been having this issue a while now. Every time I open poweramp wavelet automatically detects it. The issue is that it doesn't get undetected when there is no music playing or even when the music player is stopped which means that every time I open poweramp it gets stacked and in the notification bar it shows something like "Poweramp(2x)" and I have to force stop wavelet. Is this something I should worry about?

**Comment by Pittvandewitt** [comment]
This happens when a music player (in this case Poweramp) does not close its sessions properly. I will experiment with a change that will allow 1 session per application maximum to clear and remove these unused sessions, but I can't fix something that is not implemented correctly in a different application.
RAM usage and maybe battery consumption will go up a bit when more sessions are active, but nothing to worry about.

**Comment by BillisC** [comment]
Your update did the trick. It still shows poweramp but it's because it is running in the background. Nice work
