### ISSUE TITLE
Are the premium features permanent?

### ISSUE THREAD

**Issue by KhoryYT** [Pittvandewitt/Wavelet#36]
When buying the premium features are they permanent or are they a subscription?

**Comment by Pittvandewitt** [comment]
The paid features can be unlocked through a one-time purchase. The purchase is tied to your Google account, so if you plan to switch devices, Wavelet will still be unlocked as long as you log in with the same Google account.

**Comment by gbdomubpkm** [comment]
Hello @Pittvandewitt 

Your app is efficient and of high quality, even for the free version. Thanks for your great work.

Having an alternative degoogled android smartphone, is it possible to support you by purchasing your app outside the google playstore in order to unlock the premium features ? If so, what is the procedure?

Best regards
