### ISSUE TITLE
Notification identifies Apple Music session but AUTOEQ and other features not working when listening to music on Android

### ISSUE THREAD

**Issue by NomaanMalick** [Pittvandewitt/Wavelet#43]
I restarted my phone, cleared cache of the Apple Music app, and cleared both the cache and data of Wavelet. It still doesn't work. But it works fine with Poweramp.

**Comment by Pittvandewitt** [comment]
This is ultimately an issue with Apple Music not using the broadcasted audio session for its own music session. I have filed a bug report to Apple Music back in the summer but haven't heard back from them since. On top of that, Apple music never closes its audio sessions. Because of this, Wavelet is never told to release the audio effects and close the notification.

As a workaround for Apple Music not being processed at all, I will allow up to 2 active sessions per music application.

**Comment by Pittvandewitt** [comment]
This issue is fixed in the build available in the beta channel
