### ISSUE TITLE
Configuration resetting from time to time

### ISSUE THREAD

**Issue by Freesail21** [Pittvandewitt/Wavelet#47]
For some reason it tends to default to normal often, and it's difficult resetting custom EQ settings every time.

**Comment by Pittvandewitt** [comment]
Instead of introducing a workaround to an issue, I'd rather solve the issue. Could you please provide steps to reproduce the issue  you experience (for example when switching from a Bluetooth device to the internal speaker) and more information such as what device you are using and if you have legacy mode enabled etc.

**Comment by Pittvandewitt** [comment]
This should be fixed in the build that will be available in a few hours in the beta channel.
