### ISSUE TITLE
Permanent notification since v21.02

### ISSUE THREAD

**Issue by auanasgheps** [Pittvandewitt/Wavelet#58]
Hi,
Since the update 21.02 there's a permanent notification that cannot be dismissed even if there's nothing being played.
If I kill the app it goes away, but that's temporary until I use the app again.

Before the update I was able to dismiss it when done.

Android 11, OnePlus 8T.

**Comment by Pittvandewitt** [comment]
The notification can be dismissed if all opened audio sessions are closed by their music applications. Unfortunately many music applications do not do this properly.
Currently there is a cosmetic bug where the no applications are listed in the notification, making it look like no sessions are processed which may actually not be the case. This issue will be fixed in the next release.

**Comment by auanasgheps** [comment]
I just use Shuttle or Spotify.
Force killed both of them but the notification is still un-dismissable...

**Comment by Pittvandewitt** [comment]
By force killing a music application you deny it from closing its audio sessions properly, which results in sessions never getting closed in Wavelet. This will make the notification undismissable indeed.
