### ISSUE TITLE
Apple Music not being recognized again.

### ISSUE THREAD

**Issue by GittyMac** [Pittvandewitt/Wavelet#59]
I'm on the latest Apple Music and Wavelet beta. Apple Music is once again not being detected by Wavelet.

**Comment by Pittvandewitt** [comment]
First make sure auto start is enabled on your device if it has such a feature: https://dontkillmyapp.com/
If that does not fix the issue after performing a reboot, please share which version of Apple Music you are using. I would also like to know if Apple music is listed in the notification from Wavelet.

**Comment by GittyMac** [comment]
I am on a Google Pixel 4 on the latest security update. I am on Apple Music 3.5.0-beta and Wavelet 21.03. There is no notification and I have disabled Battery Optimization.

**Comment by Pittvandewitt** [comment]
This issue will be closed since you do no longer experience the initial issue and I was not able to reproduce it on both the stable version of Apple music and 3.5.0-beta.
Perhaps you had to restart Apple music after updating Wavelet. Updating Wavelet will cause the app to restart and lose track of ongoing sessions.
