### ISSUE TITLE
Loud noise when clicking 'reduce clipping'

### ISSUE THREAD

**Issue by Pittvandewitt** [Pittvandewitt/Wavelet#61]
Few users seem to be plagued by a loud noise when clipping reduction is toggled.
Reported from a user using a OnePlus 6.
Need help from users experiencing similar issues.

A solution may be to significantly reduce input gain before releasing and/or initializing the DP driver.

**Comment by bhatiak2050** [comment]
I can confirm that this issue is present.
Running on a Moto G 5G.

**Comment by farvell** [comment]
I can confirm as well on my OnePlus 5t (unrooted, stock everything). In my case the volume gets fixed to a certain value, probably maximum like bhatiak, but I'm not quite sure. This only happens when the setting is toggled on or off while playing back audio, and it doesn't matter whether the phone is muted or not. The volume slider will stay wherever it was before the setting is toggled. The app exhibits the same behaviour when it gets activated while playing back audio as well.

**Comment by NomisIV** [comment]
I also get this issue on a rooted Samsung Galaxy S8 running Lineage OS 17.1

**Comment by gulinfu** [comment]
I don't know what's `clipping reduction`, but I'm experiencing distortion during loud volume.
build: 21.07
device: xiaomi mi8 
os: lineageos 18.1 unrooted with legacy mode

I believe the reason being at some frequency, the volume is larger than 0 db spl after auto EQ.
when I look at my eq profile: https://github.com/jaakkopasanen/AutoEq/blob/master/results/oratory1990/harman_over-ear_2018/Sony%20WH-1000XM3/Sony%20WH-1000XM3%20GraphicEQ.txt

all adjustment is a negative number, meaning the curve after EQ would totally below 0 db to avoid clipping.
But looking at the profile curve in the app, a part of the frequency is above 0db.(is it just a visual thing or the numbers are actually adjusted?)

I've tried the limiter but it's giving me an inconsistent feeling of volume, and the post-gain is limited within 5 db, which is not enough for some eq curve.
a simple preamp with negative gain would solve this problem.
Please let me know if there is an existing solution for this. thanks

**Comment by Pittvandewitt** [comment]
I received reports that this issue is resolved with the september update (21.09). Feel free to reopen if the issue still appears in this build.
