### ISSUE TITLE
Autoeq not effective below 150Hz/70Hz

### ISSUE THREAD

**Issue by datibor** [Pittvandewitt/Wavelet#66]
Hi, I created some custom autoeq profiles and everything works except below 150Hz. Seems to be ignoring parameters below 150Hz, Sometimes i can hear some difference, but not sure what happens. If I enable "reduce clipping" the lowest working frequency band is 70Hz. Is this normal? Checked with a spectrum analyser app. Using legacy mode. Any ideea?

**Comment by datibor** [comment]
Test file content, -10dB dips at 34 50 70 97 151Hz
![Screenshot_2021-04-04-07-24-31-598_com ghisler android TotalCommander](https://user-images.githubusercontent.com/80484824/113498739-67504680-9518-11eb-82dc-7be0544e25f1.jpg)

Imported
![Screenshot_2021-04-04-07-27-10-055_com pittvandewitt wavelet](https://user-images.githubusercontent.com/80484824/113498744-733c0880-9518-11eb-9015-0c29ebc76e3f.jpg)

Sweep gerator setup
![Screenshot_2021-04-04-07-27-47-750_com android chrome](https://user-images.githubusercontent.com/80484824/113498749-78995300-9518-11eb-83cb-5584fc797d57.jpg)

Default sweep response as baseline, it's an old phone with clipped between the earpeices of a headphone.
![default response](https://user-images.githubusercontent.com/80484824/113498756-80f18e00-9518-11eb-93f1-5b17fdf6ac67.jpeg)

Sweep response if "reduce clipping" is off
![test3 reduce clipping off](https://user-images.githubusercontent.com/80484824/113498760-8b138c80-9518-11eb-8eb2-22afe1971608.jpeg)

Sweep response if "reduce clipping" is on
![test3 reduce clipping on](https://user-images.githubusercontent.com/80484824/113498762-8f3faa00-9518-11eb-9a08-62ebcbfa7031.jpeg)

Also i figured out that some parameters seems to adjust the whole 20-150hz band, not sure.

**Comment by Pittvandewitt** [comment]
First of all, thank you for the extensive information provided.
When clipping reduction is enabled, the library used will process audio in a larger timeframe, allowing for better precision. Because you defined extreme quality factors in the lower frequencies, the library struggles to process them in the given timeframe.
I expect the changes you make to show up in your measurement if you define more realistic peaks/dips in the lower frequencies, combined with clipping reduction enabled. For example in this snippet: `GraphicEQ: 20 0; 21 0; 22 0; 23 0; 24 0; 26 0; 27 0; 29 0; 30 0; 32 0; 34 0; 36 0; 38 0; 40 0; 43 0; 45 0; 48 0; 50 0; 53 0; 56 0; 59 0; 63 0; 66 0; 70 -0.1; 74 -0.4; 78 -0.7; 83 -1.3; 87 -2.1; 92 -0.8; 97 -0.5; 103 -0.2; 109 -0.1; 115 0; 121 0; 128 0;`
In practice there is no headphone that would need correction with such extreme quality factors in the lower frequencies, except for maybe the [SkullCrushers](https://github.com/jaakkopasanen/AutoEq/tree/master/results/headphonecom/headphonecom_harman_over-ear_2018/Skullcandy%20SkullCrushers%20Max%20Bass#graphs), but that belongs to a different discussion.

**Comment by datibor** [comment]
Well, yes, I know this app was intended for headphones but like everybody else, I use it also for several other things like: bluetooth speakers, my DIY car audio, my DIY home audio setup. My initial intention is was to create an infrasound filter at 30Hz where the autoeq failed. 
It works exceptionally great with my JBL charge 3, this app squeezes out some nice deep (55-65Hz) bass from it.

**Comment by datibor** [comment]
Just an ideea: what if you feed the previous buffers to the library. This could improve the frequency response by a lot. Let's say you feed normally 50ms of data. By implementing a simple FIFO buffer you can keep in memory the last 500ms of audio buffer. You call the library every 50ms. Instead of giving to the library 50ms of data, you give the 50ms+ last 500ms. When the library finishes the processing you output just the 50ms, and you ignore the rest of it. Does it make sense? It's just an example. From my opinion giving a larger buffer should help the FFT algorithms.

**Comment by datibor** [comment]
This ideea may help to reduce further the audio delay. 
But i'm not sure why the eq causes delay in the first place.

**Comment by Pittvandewitt** [comment]
How much I appreciate you thinking along to help resolving the issue, the only parameter that has influence on it can already be controlled with the clipping reduction setting. Unfortunately the library does not provide any other setting that could possibly resolve it.

**Comment by datibor** [comment]
Well if you use a precompiled library, then I understand that you can't do a lot about this issue. But if you have the full sourcecode, it's a creative challenge :)

**Comment by Taudris** [comment]
@datibor, this issue can't be resolved in a good way because Wavelet and other non-root solutions cannot load custom code into the audio processing pipeline (which is what ViPER4Android and JamesDSP are doing). Only the existing Android APIs may be used, and they don't provide for any truly custom DSP capabilities. It sounds like, from reading other issues on this repo, Wavelet primarily uses [this API which is built into Android](https://developer.android.com/reference/android/media/audiofx/DynamicsProcessing), which is really just an EQ API that lets you specify as many freq/gain pairs as you want. (Too bad there's no Q parameter...)

@Pittvandewitt, how are you implementing the delay? Could you expose a delay slider or textbox in the UI? This would allow interested users to have finer control over lower frequencies by accepting a longer delay. Bonus points for indicating the minimum controllable frequency.

**Comment by datibor** [comment]
Hi Taudris,
I ran throught the documentation, and everything checks out and now I understand that it's a heavy api limitation. iI did not see anything referring the buffer size but probably i missed it. Thanks for clarifying!

**Comment by Pittvandewitt** [comment]
Unfortunately I have to close this issue, because it is not possible for me to fix. The only way to reduce the symptoms of this issue is by enabling clipping reduction.

**Comment by Pittvandewitt** [comment]
@Taudris The delay must be set before the audio effects are initialized. Currently the switch allows for setting it at 22ms or 170ms.
I think your suggestion to add a slider for more control is fair, so I will take this into consideration. Adding the frequency may not happen though, because the setting controls more than just that.
