### ISSUE TITLE
Audio leak in speaker mode 

### ISSUE THREAD

**Issue by hugodcpires** [Pittvandewitt/Wavelet#9]
Use Wavelet without headphones (speaker mode) and set speaker volume to mute. Play something on Spotify (no sound will come out of speaker, of course). Enable and disable the Graphic equalizer. You'll hear a "flash" of sound even if the volume is in silent.

**Comment by Pittvandewitt** [comment]
Hello,

Thank you for your input. I experience this too but have not considered it to be an issue until now. It is caused by the Android audio framework buffer, something deeper in Android than on app level on which Wavelet is operating. I will do some experimenting and see if I'll be able to find a workaround.


Kind regards,

pittvandewitt
________________________________
Van: hugodcpires <notifications@github.com>
Verzonden: dinsdag 19 mei 2020 14:19
Aan: Pittvandewitt/Wavelet <Wavelet@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [Pittvandewitt/Wavelet] Audio leak in speaker mode (#9)


Use Wavelet without headphones (speaker mode) and set speaker volume to mute. Play something on Spotify (no sound will come out of speaker, of course). Enable and disable the Graphic equalizer. You'll hear a "flash" of sound even if the volume is in silent.

**Comment by hugodcpires** [comment]
Hey,A possible case where it may be a bigger issue is if the listener has some private/sensitive content going on (hence why it's silenced) and it leaks. The leak is very short but perhaps enough to draw some weird looks 😅I'm not sure if happens with headphones plugged (haven't tried) but on the speaker it seems to come up at a reasonably high volume. If it happens on headphones I suppose it can be a bit of a scare.Best, Hugo Best, Hugo On 19 May 2020 16:00, "Thomas W." <notifications@github.com> wrote:

Hello,



Thank you for your input. I experience this too but have not considered it to be an issue until now. It is caused by the Android audio framework buffer, something deeper in Android than on app level on which Wavelet is operating. I will do some experimenting and see if I'll be able to find a workaround.





Kind regards,



pittvandewitt

________________________________

Van: hugodcpires <notifications@github.com>

Verzonden: dinsdag 19 mei 2020 14:19

Aan: Pittvandewitt/Wavelet <Wavelet@noreply.github.com>

CC: Subscribed <subscribed@noreply.github.com>

Onderwerp: [Pittvandewitt/Wavelet] Audio leak in speaker mode (#9)





Use Wavelet without headphones (speaker mode) and set speaker volume to mute. Play something on Spotify (no sound will come out of speaker, of course). Enable and disable the Graphic equalizer. You'll hear a "flash" of sound even if the volume is in silent.

**Comment by Pittvandewitt** [comment]
The september update (21.09) includes some changes regarding how audio effects are initialized. Users have reported that the issue no longer occurs in this build. Feel free to reopen if you feel the issue still persists.
